/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tr_pae_2;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Markus
 */
public class Page_admin extends javax.swing.JFrame {

    /**
     * Creates new form page_barang
     */
    Connection connection;

    public Page_admin() {
        initComponents();
        koneksi();
        load_all();
        LoadGroupUser();
        LoadDataUser("");
        Load_DataBarang("");
        loadDataPelanggan("");
        LoadDataToko("");
        load_stok_barang("");
    }

    private void koneksi() {
        try {
            MysqlDataSource ds = new MysqlDataSource();
            ds.setServerName("localhost");
            ds.setDatabaseName("db_sales");
            ds.setUser("root");
            ds.setPort(3306);
            connection = (Connection) ds.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void load_all() {
        try {
            String sql = "SELECT Group_Id FROM group_barang";
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            List<String> record = new ArrayList<String>();
            while (rs.next()) {
                record.add(rs.getString(1));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(record.toArray());
            cbox_barang_groupBarang.setModel(model);

            sql = "SELECT Id_Toko FROM toko";
            stm = connection.prepareStatement(sql);
            rs = stm.executeQuery();
            List<String> record_1 = new ArrayList<String>();
            while (rs.next()) {
                record_1.add(rs.getString(1));
            }
            model = new DefaultComboBoxModel(record_1.toArray());
            cbox_stok_idtoko.setModel(model);

            sql = "SELECT Id_Barang FROM barang";
            stm = connection.prepareStatement(sql);
            rs = stm.executeQuery();
            List<String> record_2 = new ArrayList<String>();
            while (rs.next()) {
                record_2.add(rs.getString(1));
            }
            model = new DefaultComboBoxModel(record_2.toArray());
            cbox_stok_idbarang.setModel(model);

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_CariCustomer = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbox_barang_groupBarang = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();
        btn_barang_edit = new javax.swing.JButton();
        btn_barang_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_barang_IdBarang = new javax.swing.JTextField();
        text_barang_NamaBarang = new javax.swing.JTextField();
        text_barang_HargaBarang = new javax.swing.JTextField();
        btn_barang_submit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        text_CariBarang = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        text_pelanggan_cari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_DataPelanggan = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btn_customer_add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_customer_IdCustomer = new javax.swing.JTextField();
        text_customer_nama = new javax.swing.JTextField();
        text_customer_alamat = new javax.swing.JTextField();
        btn_customer_submit = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbox_customer_JenisKelamin = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        text_CariUser = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_DataUser = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        text_user_nama = new javax.swing.JTextField();
        text_user_confirm_password = new javax.swing.JTextField();
        cbox_user_groupUser = new javax.swing.JComboBox();
        btn_user_submit = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        text_user_alamat = new javax.swing.JTextField();
        text_user_password = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbox_user_jeniskelamin = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        text_user_username = new javax.swing.JTextField();
        btn_user_delete = new javax.swing.JButton();
        btn_user_add = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        text_CariToko = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_DataToko = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text_toko_wilayah = new javax.swing.JTextField();
        text_toko_nama = new javax.swing.JTextField();
        text_toko_IdToko = new javax.swing.JTextField();
        btn_toko_submit = new javax.swing.JButton();
        btn_toko_delete = new javax.swing.JButton();
        btn_toko_add = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        text_CariTransaksi = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        btn_transaksi_rekapitulasi = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        text_stok_cari_toko = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_stok_barang = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        text_stok_qty = new javax.swing.JTextField();
        btn_stok_submit = new javax.swing.JButton();
        cbox_stok_idtoko = new javax.swing.JComboBox();
        cbox_stok_idbarang = new javax.swing.JComboBox();
        btn_stok_add_barang = new javax.swing.JButton();
        btn_stok_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel1.setText("Group Barang : ");

        cbox_barang_groupBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_barang_groupBarangActionPerformed(evt);
            }
        });

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_barang.setToolTipText("");
        table_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_barang);

        btn_barang_edit.setText("Add Barang");
        btn_barang_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barang_editActionPerformed(evt);
            }
        });

        btn_barang_delete.setText("Delete");
        btn_barang_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barang_deleteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tambah / Edit Data Barang"));

        jLabel2.setText("ID Barang :");

        jLabel3.setText("Nama Barang :");

        jLabel5.setText("Harga :");

        btn_barang_submit.setText("Submit");
        btn_barang_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barang_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_barang_submit)
                    .addComponent(text_barang_HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_barang_NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_barang_IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_barang_IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_barang_NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_barang_HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_barang_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Cari Data Barang : ");

        text_CariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_CariBarangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbox_barang_groupBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(text_CariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 553, Short.MAX_VALUE)
                                .addComponent(btn_barang_edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_barang_delete)
                                .addGap(3, 3, 3))))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(text_CariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_barang_edit)
                        .addComponent(btn_barang_delete)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbox_barang_groupBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Data Barang", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Cari Data Customer : ");

        text_pelanggan_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_pelanggan_cariKeyReleased(evt);
            }
        });

        table_DataPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pelanggan", "Nama", "Alamat", "Utang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DataPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_DataPelanggan);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_customer_add.setText("Add Customer");
        btn_customer_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_addActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Insert Data Customer"));

        jLabel7.setText("ID Customer : ");

        jLabel8.setText("Nama : ");

        jLabel9.setText("Alamat : ");

        btn_customer_submit.setText("Submit");
        btn_customer_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customer_submitActionPerformed(evt);
            }
        });

        jLabel22.setText("Jenis Kelamin : ");

        cbox_customer_JenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "laki-laki", "perempuan" }));
        cbox_customer_JenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_customer_JenisKelaminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_customer_JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_customer_submit)
                    .addComponent(text_customer_alamat)
                    .addComponent(text_customer_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_customer_IdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_customer_IdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text_customer_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(text_customer_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbox_customer_JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btn_customer_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_pelanggan_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_customer_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(text_pelanggan_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(btn_customer_add)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Data Customer", jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Cari Data User : ");

        text_CariUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_CariUserKeyReleased(evt);
            }
        });

        table_DataUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jenis Kelamin", "Tanggal Masuk", "Alamat", "Username", "Password", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DataUserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_DataUser);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Insert Data User"));

        jLabel12.setText("Username : ");

        jLabel13.setText("Confirm Password : ");

        jLabel14.setText("Group User : ");

        cbox_user_groupUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_user_groupUserMouseClicked(evt);
            }
        });
        cbox_user_groupUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_user_groupUserActionPerformed(evt);
            }
        });

        btn_user_submit.setText("Submit");
        btn_user_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_submitActionPerformed(evt);
            }
        });

        jLabel19.setText("Alamat : ");

        jLabel20.setText("Password : ");

        jLabel21.setText("Jenis Kelamin : ");

        cbox_user_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));

        jLabel24.setText("Nama : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_user_submit)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbox_user_groupUser, javax.swing.GroupLayout.Alignment.LEADING, 0, 161, Short.MAX_VALUE)
                            .addComponent(text_user_password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_user_jeniskelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_user_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_user_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_user_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_user_username, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(text_user_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(text_user_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(text_user_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(text_user_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_user_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(cbox_user_groupUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(cbox_user_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_user_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_user_delete.setText("Delete");
        btn_user_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_deleteActionPerformed(evt);
            }
        });

        btn_user_add.setText("Add User");
        btn_user_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_CariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_user_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_user_delete)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(text_CariUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_user_delete)
                    .addComponent(btn_user_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Data User", jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Cari Data Toko : ");

        text_CariToko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_CariTokoKeyReleased(evt);
            }
        });

        table_DataToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Toko", "Nama Toko", "Wilayah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_DataToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DataTokoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_DataToko);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Insert Data Toko"));

        jLabel16.setText("ID Toko : ");

        jLabel17.setText("Nama Toko : ");

        jLabel18.setText("Nama Wilayah : ");

        btn_toko_submit.setText("Submit");
        btn_toko_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toko_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_toko_submit)
                    .addComponent(text_toko_wilayah, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_toko_IdToko, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_toko_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(text_toko_IdToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(text_toko_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(text_toko_wilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_toko_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_toko_delete.setText("Delete");
        btn_toko_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toko_deleteActionPerformed(evt);
            }
        });

        btn_toko_add.setText("Add Toko");
        btn_toko_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toko_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_CariToko, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_toko_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_toko_delete)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(text_CariToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_toko_delete)
                    .addComponent(btn_toko_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Data Toko", jPanel7);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Cari ID Transaksi : ");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Wilyah Toko", "Nama Toko", "Nama Pelanggan", "ID Barang", "Nama Barang", "Quantity", "Harga Barang", "Tgl Transaksi", "Nama Kasir", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jButton13.setText("Delete");

        btn_transaksi_rekapitulasi.setText("Rekapitulasi Data barang");
        btn_transaksi_rekapitulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_rekapitulasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_CariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_transaksi_rekapitulasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(text_CariTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13)
                    .addComponent(btn_transaksi_rekapitulasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Transaksi", jPanel9);

        jLabel25.setText("Cari Toko : ");

        text_stok_cari_toko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_stok_cari_tokoKeyReleased(evt);
            }
        });

        table_stok_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Toko", "ID Toko", "ID Barang", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_stok_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stok_barangMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_stok_barang);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tambah Data Stok"));

        jLabel26.setText("ID Toko : ");

        jLabel27.setText("ID Barang : ");

        jLabel28.setText("Tambah Qty : ");

        btn_stok_submit.setText("Submit");
        btn_stok_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stok_submitActionPerformed(evt);
            }
        });

        cbox_stok_idtoko.setMaximumRowCount(99);

        cbox_stok_idbarang.setMaximumRowCount(99);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_stok_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stok_submit)
                    .addComponent(cbox_stok_idtoko, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_stok_idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbox_stok_idtoko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbox_stok_idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(text_stok_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_stok_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_stok_add_barang.setText("Add Barang Stok");
        btn_stok_add_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stok_add_barangActionPerformed(evt);
            }
        });

        btn_stok_delete.setText("Delete Stok");
        btn_stok_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stok_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_stok_cari_toko, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                        .addComponent(btn_stok_add_barang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_stok_delete))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(text_stok_cari_toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stok_add_barang)
                    .addComponent(btn_stok_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        text_CariCustomer.addTab("Stok Barang", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_CariCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_CariCustomer)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_barang_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barang_submitActionPerformed
        if (btn_barang_submit.getText().equals("Submit")) {
            try {
                String sql = "INSERT INTO barang(Id_Barang, Nama_Barang, Harga, Group_Id) VALUES(?,?,?,?)";
                PreparedStatement stm = connection.prepareStatement(sql);
                stm.setString(1, text_barang_IdBarang.getText());
                stm.setString(2, text_barang_NamaBarang.getText());

                int harga = Integer.parseInt(text_barang_HargaBarang.getText());
                stm.setInt(3, harga);
                stm.setString(4, cbox_barang_groupBarang.getSelectedItem().toString());

                if (stm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Berhasil diInput !!!!");

                }
                Load_DataBarang("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (btn_barang_submit.getText().equals("Save")) {
            try {
                String Id_Barang = text_barang_IdBarang.getText();
                String Nama_Barang = text_barang_NamaBarang.getText();
                int harga = Integer.parseInt(text_barang_HargaBarang.getText());

                String sql = "UPDATE barang "
                        + "SET Nama_Barang='" + Nama_Barang + "',Harga='" + harga + "' "
                        + "WHERE Id_Barang='" + Id_Barang + "'";
                PreparedStatement stm = connection.prepareStatement(sql);
                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil update");
                    Load_DataBarang("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("PERINGATAN!!! :: gagal update/insert data barang ::");
        }

        clearTeks();
    }//GEN-LAST:event_btn_barang_submitActionPerformed

    private void btn_customer_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_submitActionPerformed
        if (btn_customer_submit.getText().equals("Submit")) {
            try {
                String sql = "INSERT INTO pelanggan(Id_Pelanggan,Nama_Pelanggan,Alamat_Pelanggan,Id_Utang,Jenis_Kelamin) VALUES (?,?,?,Id_Utang,?)";
                PreparedStatement stm = connection.prepareStatement(sql);
                stm.setString(1, text_customer_IdCustomer.getText());
                stm.setString(2, text_customer_nama.getText());
                stm.setString(3, text_customer_alamat.getText());
                stm.setString(4, cbox_user_jeniskelamin.getSelectedItem().toString());


                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil");
                    loadDataPelanggan("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (btn_customer_submit.getText().equals("Save")) {
            try {
                String Id_Custumer = text_customer_IdCustomer.getText();
                String Nama_Custumer = text_customer_nama.getText();
                String Alamat_Custumer = text_customer_alamat.getText();
                String Jenis_Kelamin = cbox_user_jeniskelamin.getSelectedItem().toString();

                String sql = "UPDATE pelanggan SET Id_Pelanggan='" + Id_Custumer + "', Nama_Pelanggan='" + Nama_Custumer + "', Alamat_Pelanggan='" + Alamat_Custumer + "', Jenis_Kelamin='" + Jenis_Kelamin + "' WHERE Id_Pelanggan='" + Id_Custumer + "'";
                PreparedStatement stm = connection.prepareStatement(sql);
                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil update");
                    loadDataPelanggan("");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("WARNING!!! :: Update or Add Failed");
        }
    }//GEN-LAST:event_btn_customer_submitActionPerformed

    private void btn_barang_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barang_deleteActionPerformed
        try {
            int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "delete", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM barang WHERE Id_Barang=?";
                PreparedStatement stm = connection.prepareStatement(sql);
                int row = table_barang.getSelectedRow();
                String chooser = table_barang.getValueAt(row, 0).toString();
                stm.setString(1, chooser);

                if (stm.executeUpdate() > 0) {
                    Load_DataBarang("");
                    clearTeks();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_barang_deleteActionPerformed

    void clearTeks() {
        text_barang_IdBarang.setText("");
        text_barang_NamaBarang.setText("");
        text_barang_HargaBarang.setText("");

        text_customer_IdCustomer.setText("");
        text_customer_alamat.setText("");
        text_customer_nama.setText("");

        text_toko_IdToko.setText("");
        text_toko_nama.setText("");
        text_toko_wilayah.setText("");

        text_user_alamat.setText("");
        text_user_confirm_password.setText("");
        text_user_password.setText("");
        text_user_nama.setText("");
        text_user_username.setText("");

        cbox_stok_idbarang.setSelectedIndex(-1);
        cbox_stok_idtoko.setSelectedIndex(-1);
        
        text_stok_qty.setText("");
        text_stok_cari_toko.setText("");
    }

    private void btn_barang_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barang_editActionPerformed
        btn_barang_submit.setText("Submit");
        text_barang_IdBarang.setEditable(true);
        clearTeks();
    }//GEN-LAST:event_btn_barang_editActionPerformed

    private void load_stok_barang(String cari) {
        try {
            String sql = "SELECT t.Nama_Toko, s.Id_Toko, s.Id_Barang, s.QTY_barang "
                    + "FROM stock s INNER JOIN toko t "
                    + "ON t.Id_Toko = s.Id_Toko "
                    + "WHERE t.Nama_Toko LIKE '%" + cari + "%'";
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            List<Object[]> record = new ArrayList<Object[]>();
            while (rs.next()) {
                Object data[] = new Object[4];
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getInt(4);
                record.add(data);
            }
            Object tampung[][] = new Object[record.size()][5];
            int index = 0;
            for (Object[] hasil : record) {
                tampung[index] = hasil;
                index++;
            }
            String header[] = {"Nama Toko", "Id Toko", "Id Barang", "Qty Barang"};
            DefaultTableModel mode = new DefaultTableModel(tampung, header);
            table_stok_barang.setModel(mode);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Load_DataBarang(String cari) {
        try {
            String sql = "SELECT CONCAT(Group_Id, Id_Barang), Nama_Barang, Harga "
                    + "FROM barang "
                    + "WHERE Group_Id=? AND Nama_Barang LIKE '%" + cari + "%'";
            PreparedStatement stm = connection.prepareStatement(sql);
            stm.setString(1, cbox_barang_groupBarang.getSelectedItem().toString());
            ResultSet rs = stm.executeQuery();
            List<Object[]> record = new ArrayList<Object[]>();
            while (rs.next()) {
                Object data[] = new Object[3];
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                int harga = rs.getInt(3);
                data[2] = harga;
                record.add(data);
            }
            Object tampung[][] = new Object[record.size()][3];
            int index = 0;
            for (Object[] ambil : record) {
                tampung[index] = ambil;
                index++;

            }
            String header[] = {"ID Barang", "Nama Barang", "Harga"};
            DefaultTableModel model = new DefaultTableModel(tampung, header);
            table_barang.setModel(model);
        } catch (Exception e) {
        }
    }

    private void loadDataPelanggan(String cari_dataPelanggan) {
        try {
            String sql = "SELECT Id_Pelanggan,Nama_Pelanggan,Alamat_Pelanggan,Id_Utang,Jenis_Kelamin FROM pelanggan WHERE Nama_Pelanggan LIKE '%" + cari_dataPelanggan + "%' AND Id_Pelanggan <> '0'";
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            List<Object[]> record = new ArrayList<Object[]>();
            while (rs.next()) {
                Object data[] = new Object[5];
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);

                int utang = rs.getInt(4);
                data[3] = utang;
                data[4] = rs.getString(5);
                record.add(data);
            }

            Object tampung[][] = new Object[record.size()][5];
            int index = 0;
            for (Object[] hasil : record) {
                tampung[index] = hasil;
                index++;
            }
            String header[] = {"ID Pelanggan", "Nama", "Alamat", "ID Utang", "Jenis Kelamin"};
            DefaultTableModel mode = new DefaultTableModel(tampung, header);
            table_DataPelanggan.setModel(mode);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataToko(String cari_dataToko) {
        try {
            String sql = "SELECT Id_Toko,Nama_Toko,Wilayah_Toko FROM toko WHERE Nama_Toko LIKE '%" + cari_dataToko + "%'";
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            List<Object[]> record = new ArrayList<Object[]>();
            while (rs.next()) {
                Object data[] = new Object[3];
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                record.add(data);
            }
            Object tampung[][] = new Object[record.size()][3];
            int index = 0;
            for (Object[] object : record) {
                tampung[index] = object;
                index++;
            }

            String header[] = {"ID Toko", "Nama Toko", "Wiliayah Toko"};
            DefaultTableModel model1 = new DefaultTableModel(tampung, header);
            table_DataToko.setModel(model1);


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadGroupUser() {
        try {
            String sql = "SELECT Group_Id,Keterangan_User FROM group_user";
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            List<String> record = new ArrayList<String>();
            while (rs.next()) {
                record.add(rs.getString(1));
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(record.toArray());
            cbox_user_groupUser.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataUser(String cari_data_user) {
        try {
            String sql = "SELECT Nama, Jenis_Kelamin, Tanggal_Masuk_Kerja, Alamat, User_Name, Password, Group_Id FROM tb_user WHERE Group_Id=? AND Nama LIKE '%" + cari_data_user + "%'";
            PreparedStatement stm = connection.prepareStatement(sql);
            stm.setString(1, cbox_user_groupUser.getSelectedItem().toString());
            ResultSet rs = stm.executeQuery();
            List<Object[]> record = new ArrayList<Object[]>();
            while (rs.next()) {
                Object[] data = new Object[7];
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getDate(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                record.add(data);
            }
            Object[][] tampung = new Object[record.size()][5];
            int index = 0;
            for (Object[] hasil : record) {
                tampung[index] = hasil;
                index++;
            }
            String header[] = {"Nama", "Jenis Kelamin", "Tanggal Masuk", "Alamat", "Username", "Password", "Keterangan"};
            DefaultTableModel model = new DefaultTableModel(tampung, header);
            table_DataUser.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void table_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_barangMouseClicked
        btn_barang_submit.setText("Save");
        text_barang_IdBarang.setEditable(false);
        text_barang_IdBarang.setText(table_barang.getValueAt(table_barang.getSelectedRow(), 0).toString());
        text_barang_NamaBarang.setText(table_barang.getValueAt(table_barang.getSelectedRow(), 1).toString());
        text_barang_HargaBarang.setText(table_barang.getValueAt(table_barang.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_table_barangMouseClicked

    private void cbox_barang_groupBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_barang_groupBarangActionPerformed
        Load_DataBarang("");
    }//GEN-LAST:event_cbox_barang_groupBarangActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "delete", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM pelanggan WHERE Id_Pelanggan=?";
                PreparedStatement stm = connection.prepareStatement(sql);
                int row = table_DataPelanggan.getSelectedRow();
                String chooser = table_DataPelanggan.getValueAt(row, 0).toString();
                stm.setString(1, chooser);

                if (stm.executeUpdate() > 0) {
                    loadDataPelanggan("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_DataTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DataTokoMouseClicked
        btn_toko_submit.setText("Save");
        text_toko_IdToko.setEditable(false);
        text_toko_IdToko.setText(table_DataToko.getValueAt(table_DataToko.getSelectedRow(), 0).toString()); // sek
        text_toko_nama.setText(table_DataToko.getValueAt(table_DataToko.getSelectedRow(), 1).toString());
        text_toko_wilayah.setText(table_DataToko.getValueAt(table_DataToko.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_table_DataTokoMouseClicked

    private void btn_toko_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toko_addActionPerformed
        btn_toko_submit.setText("Submit");
        text_toko_IdToko.setEditable(true);
        clearTeks();
    }//GEN-LAST:event_btn_toko_addActionPerformed

    private void btn_toko_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toko_deleteActionPerformed
        try {
            int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "delete", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM toko WHERE Id_Toko=?";
                PreparedStatement stm = connection.prepareStatement(sql);
                int row = table_DataToko.getSelectedRow();
                String chooser = table_DataToko.getValueAt(row, 0).toString();
                stm.setString(1, chooser);

                if (stm.executeUpdate() > 0) {
                    LoadDataToko("");
                    clearTeks();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }




    }//GEN-LAST:event_btn_toko_deleteActionPerformed

    private void btn_customer_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_addActionPerformed
        btn_customer_submit.setText("Submit");
        text_customer_IdCustomer.setEditable(true);
        clearTeks();
    }//GEN-LAST:event_btn_customer_addActionPerformed

    private void btn_user_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_addActionPerformed
        clearTeks();
        btn_user_submit.setText("Submit");
        text_user_username.setEditable(true);
    }//GEN-LAST:event_btn_user_addActionPerformed

    private void btn_user_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_deleteActionPerformed
        try {
            int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "delete", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM tb_user WHERE Nama=?";
                PreparedStatement stm = connection.prepareStatement(sql);
                int row = table_DataUser.getSelectedRow();
                String chooser = table_DataUser.getValueAt(row, 0).toString();
                stm.setString(1, chooser);

                if (stm.executeUpdate() > 0) {
                    LoadDataUser("");
                    System.out.println("berhasil");
                    clearTeks();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }



    }//GEN-LAST:event_btn_user_deleteActionPerformed

    private void text_CariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_CariBarangKeyReleased
        Load_DataBarang(text_CariBarang.getText().toLowerCase().toString());
    }//GEN-LAST:event_text_CariBarangKeyReleased

    private void table_DataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DataPelangganMouseClicked
        btn_customer_submit.setText("Save");
        text_customer_IdCustomer.setEditable(false);
        String header[] = {"ID Pelanggan", "Nama", "Alamat", "Utang", "Jenis Kelamin"};
        text_customer_IdCustomer.setText(table_DataPelanggan.getValueAt(table_DataPelanggan.getSelectedRow(), 0).toString()); // sek
        text_customer_nama.setText(table_DataPelanggan.getValueAt(table_DataPelanggan.getSelectedRow(), 1).toString());
        text_customer_alamat.setText(table_DataPelanggan.getValueAt(table_DataPelanggan.getSelectedRow(), 2).toString());


    }//GEN-LAST:event_table_DataPelangganMouseClicked

    private void table_DataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DataUserMouseClicked
        btn_user_submit.setText("Save");
        text_user_username.setEditable(false);
        String header[] = {"Nama", "Jenis Kelamin", "Tanggal Masuk", "Alamat", "Username", "Password", "Keterangan"};
        text_user_nama.setText(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 0).toString());
        cbox_user_jeniskelamin.setSelectedItem(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 1).toString());
        text_user_alamat.setText(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 3).toString()); // sek
        text_user_username.setText(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 4).toString());
        text_user_password.setText(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 5).toString());
        cbox_user_groupUser.setSelectedItem(table_DataUser.getValueAt(table_DataUser.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_table_DataUserMouseClicked

    private void btn_user_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_submitActionPerformed
        if (text_user_nama.getText().equals("") || text_user_password.getText().equals("") || text_user_username.getText().equals("") || text_user_alamat.getText().equals("") || text_user_confirm_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "field ada yang kosong !!!!");
        } else if (text_user_password.getText().equals(text_user_confirm_password)) {
            JOptionPane.showMessageDialog(this, "password tidak sama");
        } else if (btn_user_submit.getText().equals("Submit")) {
            try {
                String sql = "INSERT INTO tb_user(User_Name, Password, Group_Id, Nama, Jenis_Kelamin, Tanggal_Masuk_Kerja, Alamat) VALUES (?,?,?,?,?,CURDATE(),?)";
                PreparedStatement stm = connection.prepareStatement(sql);
                stm.setString(1, text_user_username.getText());
                stm.setString(2, text_user_password.getText());
                stm.setString(3, cbox_user_groupUser.getSelectedItem().toString());
                stm.setString(4, text_user_nama.getText());
                String jeniskelamin = cbox_user_jeniskelamin.getSelectedItem().toString();
                stm.setString(5, jeniskelamin);
                stm.setString(6, text_user_alamat.getText());
                if (stm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan !!!!!");
                    LoadDataUser("");
                }
                clearTeks();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (btn_user_submit.getText().equals("Save")) {

            try {
                String User_Name = text_user_username.getText();
                String Password = text_user_password.getText();
                String Group_Id = cbox_user_groupUser.getSelectedItem().toString();
                String nama = text_user_nama.getText();
                String jeniskelamin = cbox_user_jeniskelamin.getSelectedItem().toString();
                String alamat = text_user_alamat.getText();
                String confirm = text_user_confirm_password.getText();
                String sql = "UPDATE tb_user SET User_Name = '" + User_Name + "', Password='"
                        + Password + "', Group_Id = '" + Group_Id + "', Nama = '" + nama + "', Jenis_Kelamin = '"
                        + jeniskelamin + "', Alamat = '" + alamat + "' WHERE User_Name = '" + User_Name + "' ";
                PreparedStatement stm = connection.prepareStatement(sql);
                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil update");
                    LoadDataUser("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("WARNING!!! :: Update or Add Failed");
        }
        LoadDataUser("");
    }//GEN-LAST:event_btn_user_submitActionPerformed

    private void cbox_user_groupUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_user_groupUserMouseClicked
    }//GEN-LAST:event_cbox_user_groupUserMouseClicked

    private void btn_toko_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toko_submitActionPerformed
        if (btn_toko_submit.getText().equals("Submit")) {
            try {
                String sql = "INSERT INTO toko(Id_Toko,Nama_Toko,Wilayah_Toko)VALUES (?,?,?)";
                PreparedStatement stm = connection.prepareStatement(sql);
                stm.setString(1, text_toko_IdToko.getText());
                stm.setString(2, text_toko_nama.getText());
                stm.setString(3, text_toko_wilayah.getText());

                if (stm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Berhasil diInput !!!!");
                    LoadDataToko("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearTeks();
        } else if (btn_toko_submit.getText().equals("Save")) {
            try {
                String Id_Toko = text_toko_IdToko.getText();
                String Nama_Toko = text_toko_nama.getText();
                String Nama_Wilayah = text_toko_wilayah.getText();

                String sql = "UPDATE toko SET Id_Toko = '" + Id_Toko + "', Nama_Toko='"
                        + Nama_Toko + "', Wilayah_Toko = '" + Nama_Wilayah + "' WHERE Id_Toko = '" + Id_Toko + "' ";

                PreparedStatement stm = connection.prepareStatement(sql);


                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil update");
                    LoadDataToko("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            clearTeks();
        }
    }//GEN-LAST:event_btn_toko_submitActionPerformed

    private void text_pelanggan_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_pelanggan_cariKeyReleased
        loadDataPelanggan(text_pelanggan_cari.getText().toString());
    }//GEN-LAST:event_text_pelanggan_cariKeyReleased

    private void cbox_customer_JenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_customer_JenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_customer_JenisKelaminActionPerformed

    private void cbox_user_groupUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_user_groupUserActionPerformed
        LoadDataUser("");

    }//GEN-LAST:event_cbox_user_groupUserActionPerformed

    private void text_CariUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_CariUserKeyReleased
        LoadDataUser(text_CariUser.getText().toString());
    }//GEN-LAST:event_text_CariUserKeyReleased

    private void text_CariTokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_CariTokoKeyReleased
        LoadDataToko(text_CariToko.getText().toString());
    }//GEN-LAST:event_text_CariTokoKeyReleased

    private void btn_stok_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stok_submitActionPerformed
        String id_toko = cbox_stok_idtoko.getSelectedItem().toString();
        String id_barang = cbox_stok_idbarang.getSelectedItem().toString();
        
        if (btn_stok_submit.getText().equals("Save")) {
            try {
                String qty = text_stok_qty.getText();

                String sql = "UPDATE stock SET QTY_Barang = (QTY_Barang + " + qty + ") "
                        + "WHERE Id_Toko = '" + id_toko + "' "
                        + "AND Id_Barang = '" + id_barang + "'";

                PreparedStatement stm = connection.prepareStatement(sql);
                 System.out.println(sql);

                if (stm.executeUpdate() > 0) {
                    System.out.println("berhasil update");
                    load_stok_barang("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                String sql = "INSERT INTO stock (Id_Toko, Id_Barang, QTY_Barang) "
                        + "VALUES (?,?,?)";
                PreparedStatement stm = connection.prepareStatement(sql);
                stm.setString(1, id_toko);
                stm.setString(2, id_barang);
                int qty = Integer.parseInt(text_stok_qty.getText().toString());
                stm.setInt(3, qty);

                if (stm.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "Berhasil diInput !!!!");
                    load_stok_barang("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        clearTeks();
    }//GEN-LAST:event_btn_stok_submitActionPerformed

    private void table_stok_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stok_barangMouseClicked
        String id_barang = table_stok_barang.getValueAt(table_stok_barang.getSelectedRow(), 2).toString();
        String id_toko = table_stok_barang.getValueAt(table_stok_barang.getSelectedRow(), 1).toString();

        jLabel28.setText("Tambah Qty : ");
        cbox_stok_idtoko.setSelectedItem(id_toko);
        cbox_stok_idbarang.setSelectedItem(id_barang);
        cbox_stok_idbarang.setEnabled(false);
        cbox_stok_idtoko.setEnabled(false);
        
        btn_stok_submit.setText("Save");
    }//GEN-LAST:event_table_stok_barangMouseClicked

    private void text_stok_cari_tokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_stok_cari_tokoKeyReleased
        String cari = text_stok_cari_toko.getText();
        load_stok_barang(cari);
    }//GEN-LAST:event_text_stok_cari_tokoKeyReleased

    private void btn_stok_add_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stok_add_barangActionPerformed
        clearTeks();
        btn_stok_submit.setText("Submit");
        cbox_stok_idbarang.setEnabled(true);
        cbox_stok_idtoko.setEnabled(true);
        jLabel28.setText("Qty : ");
    }//GEN-LAST:event_btn_stok_add_barangActionPerformed

    private void btn_stok_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stok_deleteActionPerformed
        try {
            int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == JOptionPane.YES_OPTION) {
                String sql = "DELETE "
                        + "FROM stock "
                        + "WHERE Id_Toko = ? "
                        + "AND Id_Barang = ? ";
                PreparedStatement stm = connection.prepareStatement(sql);
                String id_toko = (String) table_stok_barang.getValueAt(table_stok_barang.getSelectedRow(), 0);
                stm.setString(1, id_toko);
                String id_barang = (String) table_stok_barang.getValueAt(table_stok_barang.getSelectedRow(), 1);
                stm.setString(2, id_barang);

                if (stm.executeUpdate() > 0) {
                    load_stok_barang("");
                    clearTeks();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
//        int ok = JOptionPane.showConfirmDialog(this, "apakah yakin menghapus data? ", "delete", JOptionPane.YES_NO_CANCEL_OPTION);
//        if (ok == JOptionPane.YES_OPTION) {
//            String sql = "DELETE FROM pelanggan WHERE Id_Pelanggan=?";
//            PreparedStatement stm = connection.prepareStatement(sql);
//            int row = table_DataPelanggan.getSelectedRow();
//            String chooser = table_DataPelanggan.getValueAt(row, 0).toString();
//            stm.setString(1, chooser);
//
//            if (stm.executeUpdate() > 0) {
//                loadDataPelanggan("");
//            }
//        }
    }//GEN-LAST:event_btn_stok_deleteActionPerformed

    private void btn_transaksi_rekapitulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_rekapitulasiActionPerformed
        JOptionPane.showMessageDialog(this, "Iso di klik");
    }//GEN-LAST:event_btn_transaksi_rekapitulasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang_delete;
    private javax.swing.JButton btn_barang_edit;
    private javax.swing.JButton btn_barang_submit;
    private javax.swing.JButton btn_customer_add;
    private javax.swing.JButton btn_customer_submit;
    private javax.swing.JButton btn_stok_add_barang;
    private javax.swing.JButton btn_stok_delete;
    private javax.swing.JButton btn_stok_submit;
    private javax.swing.JButton btn_toko_add;
    private javax.swing.JButton btn_toko_delete;
    private javax.swing.JButton btn_toko_submit;
    private javax.swing.JButton btn_transaksi_rekapitulasi;
    private javax.swing.JButton btn_user_add;
    private javax.swing.JButton btn_user_delete;
    private javax.swing.JButton btn_user_submit;
    private javax.swing.JComboBox cbox_barang_groupBarang;
    private javax.swing.JComboBox cbox_customer_JenisKelamin;
    private javax.swing.JComboBox cbox_stok_idbarang;
    private javax.swing.JComboBox cbox_stok_idtoko;
    private javax.swing.JComboBox cbox_user_groupUser;
    private javax.swing.JComboBox cbox_user_jeniskelamin;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable table_DataPelanggan;
    private javax.swing.JTable table_DataToko;
    private javax.swing.JTable table_DataUser;
    private javax.swing.JTable table_barang;
    private javax.swing.JTable table_stok_barang;
    private javax.swing.JTextField text_CariBarang;
    private javax.swing.JTabbedPane text_CariCustomer;
    private javax.swing.JTextField text_CariToko;
    private javax.swing.JTextField text_CariTransaksi;
    private javax.swing.JTextField text_CariUser;
    private javax.swing.JTextField text_barang_HargaBarang;
    private javax.swing.JTextField text_barang_IdBarang;
    private javax.swing.JTextField text_barang_NamaBarang;
    private javax.swing.JTextField text_customer_IdCustomer;
    private javax.swing.JTextField text_customer_alamat;
    private javax.swing.JTextField text_customer_nama;
    private javax.swing.JTextField text_pelanggan_cari;
    private javax.swing.JTextField text_stok_cari_toko;
    private javax.swing.JTextField text_stok_qty;
    private javax.swing.JTextField text_toko_IdToko;
    private javax.swing.JTextField text_toko_nama;
    private javax.swing.JTextField text_toko_wilayah;
    private javax.swing.JTextField text_user_alamat;
    private javax.swing.JTextField text_user_confirm_password;
    private javax.swing.JTextField text_user_nama;
    private javax.swing.JTextField text_user_password;
    private javax.swing.JTextField text_user_username;
    // End of variables declaration//GEN-END:variables
}
